line-length = 88
target-version = "py311"
src = ["theo/services/api/app"]
exclude = [
    "docs",
    "tests",
    "typings",
    "scripts",
    "theo/services/cli",
    "theo/services/geo",
    "theo/services/api/tests",
]

[lint]
select = ["E", "F", "W", "B", "S", "PD", "FA", "I"]
ignore = [
    "E501",
    "E402",
    "F401",
    "F811",
    "F821",
    "F841",
    "B008",
    "B010",
    "B904",
    "B905",
    "S101",
    "S110",
    "S112",
    "S310",
    "S311",
    "S314",
]

[lint.per-file-ignores]
"tests/**" = ["S101", "S106", "E501"]
"theo/services/api/tests/**" = ["S101", "S106", "E501"]
"theo/services/cli/tests/**" = ["S101", "S106", "E501"]
"typings/**" = ["I001"]
"theo/services/geo/seed_openbible_geo.py" = ["S603", "S607", "E501", "I001"]

[lint.isort]
known-first-party = ["theo"]
combine-as-imports = true
