[tool.black]
line-length = 88
target-version = ["py311"]

[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["theo"]
combine_as_imports = true

[tool.ruff]
line-length = 88
target-version = "py311"
src = ["theo", "tests", "scripts"]
exclude = ["docs"]

[tool.ruff.lint]
select = ["E", "F", "W", "S"]
extend-select = ["I", "PD", "FA"]
ignore = ["E501"]

[tool.ruff.lint.isort]
known-first-party = ["theo"]
combine-as-imports = true

[tool.mypy]
python_version = "3.11"
files = [
    "theo/services/api/app",
    "theo/services/api/tests",
    "tests/export",
]
ignore_missing_imports = true
warn_unused_configs = true
follow_imports = "skip"

[tool.pytest.ini_options]
markers = [
    "redteam: OWASP LLM red-team regression suite",
    "no_auth_override: disable authentication override fixture for security assertions",
    "slow: slower end-to-end smoke tests",
]

[tool.ruff.lint.per-file-ignores]
"**/tests/**" = ["S101"]
"theo/services/geo/seed_openbible_geo.py" = ["S603", "S607"]
"typings/jwt/__init__.pyi" = ["I001"]
