version: '3'

tasks:
  start_api:
    cmds:
      - poetry run uvicorn theo.services.api.app.bootstrap.app_factory:create_app --factory --reload --port 8000
    silent: true

  stop_api:
    cmds:
      - pkill -f "uvicorn .*theo.services.api.app.bootstrap.app_factory" || true
    silent: true

  architecture:test:
    desc: Run architecture enforcement tests
    cmds:
      - pytest tests/architecture -q

  architecture:imports:
    desc: Validate import boundaries with import-linter
    cmds:
      - lint-imports --config importlinter.ini

  architecture:check:
    desc: Run all architecture boundary checks
    cmds:
      - task: architecture:test
      - task: architecture:imports
