version: '3'

tasks:
  start_api:
    cmds:
      - poetry run uvicorn theo.services.api.app.bootstrap.app_factory:create_app --factory --reload --port 8000
    silent: true

  stop_api:
    cmds:
      - pkill -f "uvicorn .*theo.services.api.app.bootstrap.app_factory" || true
    silent: true

  architecture:test:
    desc: Run architecture enforcement tests
    cmds:
      - pytest tests/architecture -q

  architecture:imports:
    desc: Validate import boundaries with import-linter
    cmds:
      - lint-imports --config importlinter.ini

  architecture:check:
    desc: Run all architecture boundary checks
    cmds:
      - task: architecture:test
      - task: architecture:imports

  test:fast:
    desc: Run the fast pytest suite without contract, GPU, or pgvector tests
    cmds:
      - pytest -m "not (slow or gpu or contract)"

  test:full:
    desc: Run the full pytest suite including pgvector and contract suites
    cmds:
      - pytest --schema --pgvector --contract

  deps:lock:
    desc: Regenerate pip-compile lockfiles for all extras
    cmds:
      - pip-compile --resolver=backtracking --extra base --output-file constraints/base.txt pyproject.toml
      - pip-compile --resolver=backtracking --extra api --output-file constraints/api.txt pyproject.toml
      - pip-compile --resolver=backtracking --extra ml --output-file constraints/ml.txt pyproject.toml
      - pip-compile --resolver=backtracking --extra dev --output-file constraints/dev.txt pyproject.toml
