version: '3'

tasks:
  start_api:
    cmds:
      - poetry run uvicorn theo.services.api.app:app --reload --port 8000
    silent: true

  stop_api:
    cmds:
      - pkill -f "uvicorn .*theo.services.api.app" || true
    silent: true
