"""Domain core aggregates, value objects, and business policies.

This package is intentionally framework-agnostic. Only standard library,
`dataclasses`, and `pydantic` types are permitted.
"""

from .documents import Document, DocumentId, DocumentMetadata
from .references import ScriptureReference
from .research import (
    CrossReferenceEntry,
    DssLinkEntry,
    FallacyHit,
    HistoricityEntry,
    Hypothesis,
    HypothesisDraft,
    HypothesisNotFoundError,
    MorphToken,
    OverviewBullet,
    ReliabilityOverview,
    ResearchNote,
    ResearchNoteDraft,
    ResearchNoteEvidence,
    ResearchNoteEvidenceDraft,
    ResearchNoteNotFoundError,
    VariantEntry,
    Verse,
    build_reliability_overview,
    fallacy_detect,
    fetch_cross_references,
    fetch_dss_links,
    fetch_morphology,
    fetch_passage,
    historicity_search,
    variants_apparatus,
)

__all__ = [
    "Document",
    "DocumentId",
    "DocumentMetadata",
    "ScriptureReference",
    "CrossReferenceEntry",
    "DssLinkEntry",
    "FallacyHit",
    "Hypothesis",
    "HypothesisDraft",
    "HypothesisNotFoundError",
    "HistoricityEntry",
    "MorphToken",
    "OverviewBullet",
    "ReliabilityOverview",
    "ResearchNote",
    "ResearchNoteDraft",
    "ResearchNoteEvidence",
    "ResearchNoteEvidenceDraft",
    "ResearchNoteNotFoundError",
    "VariantEntry",
    "Verse",
    "build_reliability_overview",
    "fallacy_detect",
    "fetch_cross_references",
    "fetch_dss_links",
    "fetch_morphology",
    "fetch_passage",
    "historicity_search",
    "variants_apparatus",
]
