[schema]
path = "/openapi.json"

[[suites]]
name = "ai-chat"

  [[suites.endpoints]]
  method = "POST"
  path = "/ai/chat"

  [[suites.endpoints]]
  method = "GET"
  path = "/ai/chat/{session_id}"

[[suites]]
name = "ai-exports"

  [[suites.endpoints]]
  method = "POST"
  path = "/ai/citations/export"

  [[suites.endpoints]]
  method = "POST"
  path = "/ai/sermon-prep/export"

[[suites]]
name = "ai-digest"

  [[suites.endpoints]]
  method = "GET"
  path = "/ai/digest"

  [[suites.endpoints]]
  method = "POST"
  path = "/ai/digest/watchlists"

[[suites]]
name = "ai-llm"

  [[suites.endpoints]]
  method = "GET"
  path = "/ai/llm"

[[suites]]
name = "analytics"

  [[suites.endpoints]]
  method = "POST"
  path = "/analytics/feedback"

[[suites]]
name = "documents"

  [[suites.endpoints]]
  method = "GET"
  path = "/documents/"

[[suites]]
name = "research"

  [[suites.endpoints]]
  method = "GET"
  path = "/research/notes"

[[suites]]
name = "search"

  [[suites.endpoints]]
  method = "GET"
  path = "/search/"

[[suites]]
name = "verses"

  [[suites.endpoints]]
  method = "GET"
  path = "/verses/{osis}/timeline"

[[suites]]
name = "settings"

  [[suites.endpoints]]
  method = "PUT"
  path = "/settings/ai/providers/{provider}"

[[suites]]
name = "trails"

  [[suites.endpoints]]
  method = "POST"
  path = "/trails/{trail_id}/replay"
