name: Security - OpenSSF Scorecard

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: '0 6 * * 1'

permissions:
  contents: read
  security-events: write
  actions: read
  id-token: write  # Required for OIDC-based Sigstore signing

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Run Scorecard analysis
        uses: ossf/scorecard-action@4eaacf0543bb3f2c246792bd56e8cdeffafb205a # v2.4.3
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true
          # OIDC signing is automatic with id-token: write permission

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@16140ae1a102900babc80a33c44059580f687047 # v4
        with:
          sarif_file: results.sarif

      - name: Upload Scorecard artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: scorecard-report
          path: results.sarif
          if-no-files-found: error
