name: OWASP ZAP Baseline

on:
  pull_request_target:
    branches:
      - main
  schedule:
    - cron: '30 3 * * 1'
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  zap-baseline:
    name: Scan staging API
    runs-on: ubuntu-latest
    timeout-minutes: 45
    env:
      STAGING_API_BASE_URL: ${{ secrets.STAGING_API_BASE_URL }}
    steps:
      - name: Verify staging URL secret
        id: verify-secret
        run: |
          if [ -z "${STAGING_API_BASE_URL}" ]; then
            echo "::warning::STAGING_API_BASE_URL secret is not configured. Skipping ZAP baseline scan."
            echo "skip=true" >> "$GITHUB_OUTPUT"
          else
            echo "skip=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Checkout repository
        if: steps.verify-secret.outputs.skip != 'true'
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: ${{ github.event.pull_request.base.repo.full_name || github.repository }}
          ref: ${{ github.event.pull_request.base.ref || github.ref }}

      - name: Run ZAP baseline scan
        if: steps.verify-secret.outputs.skip != 'true'
        id: zap
        uses: zaproxy/action-baseline@0619037bb784a56e2e06b104f0ebe157e076f075 # v0.13.0
        with:
          target: ${{ env.STAGING_API_BASE_URL }}
          cmd_options: '-J zap-baseline-report.json -r zap-baseline-report.html -w zap-baseline-warn.md'

      - name: Fail on high severity alerts
        if: steps.verify-secret.outputs.skip != 'true'
        run: python scripts/security/zap_severity_gate.py zap-baseline-report.json --fail-on high

      - name: Convert ZAP report to SARIF
        if: steps.verify-secret.outputs.skip != 'true'
        run: python scripts/security/zap_to_sarif.py zap-baseline-report.json zap-baseline-report.sarif

      - name: Upload SARIF to security dashboard
        if: steps.verify-secret.outputs.skip != 'true'
        uses: github/codeql-action/upload-sarif@755f44910c12a3d7ca0d8c6e42c048b3362f7cec # v3
        with:
          sarif_file: zap-baseline-report.sarif
          category: zap-baseline

      - name: Upload ZAP artifacts
        if: steps.verify-secret.outputs.skip != 'true' && always()
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        with:
          name: zap-baseline-artifacts
          path: |
            zap-baseline-report.json
            zap-baseline-report.html
            zap-baseline-warn.md
            zap-baseline-report.sarif
          if-no-files-found: warn
